name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: üì• –ö–ª–æ–Ω–∏—Ä–æ–≤–∞—Ç—å —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π
      uses: actions/checkout@v3

    - name: üì¶ –£—Å—Ç–∞–Ω–æ–≤–∏—Ç—å Android SDK –∏ –ø—Ä–∏–Ω—è—Ç—å –ª–∏—Ü–µ–Ω–∑–∏–∏
      uses: android-actions/setup-android@v2

    - name: üêç –£—Å—Ç–∞–Ω–æ–≤–∏—Ç—å Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: üß∞ –£—Å—Ç–∞–Ω–æ–≤–∏—Ç—å –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–∏
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk autoconf automake libtool pkg-config
        pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: ‚öôÔ∏è –°–±–æ—Ä–∫–∞ APK
      run: buildozer android debug

    - name: üì¶ –°–æ—Ö—Ä–∞–Ω–∏—Ç—å APK –∫–∞–∫ –∞—Ä—Ç–µ—Ñ–∞–∫—Ç
      uses: actions/upload-artifact@v4
      with:
        name: telegramparser-debug-apk
        path: bin/*.apk

